repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: python -m flake8
        types: [python]

      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: python -m isort -y
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: python -m black
        types: [python]

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: python -m mypy
        types: [python]
